cosmicsns/urls.py
from django.urls import path
from . import views
app_name='cosmicsns'
urlpatterns = [
    path('list/', views.PostsList.as_view(),name='list'),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('create/', views.UserCreateView.as_view(),name="create"),
    path('tweet/', views.TweetView.as_view(),name="tweet"),
    path('userinfo/<int:pk>', views.UserInfoView.as_view(),name='userinfo'),
    path('useredit/<int:pk>', views.UserEditView.as_view(),name='useredit'),
    path('userposts/<int:pk>', views.UserPostsView.as_view(),name='userposts'),
]

snsproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#import cosmicsns.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cosmicsns/', include('cosmicsns.urls'), name='cosmicsns'),
    path('cosmicsns/', include('django.contrib.auth.urls')),
] 

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cosmicsns/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.core.validators import FileExtensionValidator
# Create your models here.
class User(AbstractUser):
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(unique=True)
    icon = models.FileField(upload_to='profiles',blank=True, null=True, validators=[FileExtensionValidator(['jpg','png','gif','jpeg', ])],)
    introduce = models.CharField(max_length=200,blank=True, null=True)

class Posts(models.Model):
    message = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    postedtime = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.message[:10]

cosmicsns/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class LoginForm(auth_forms.AuthenticationForm):
    '''ログインフォーム'''
    def __init__(self, *args, **kw):
        super().__init__(*args, **kw)
        for field in self.fields.values():
            field.widget.attrs['placeholder'] = field.label

class RegisterForm(UserCreationForm):
 
    # 入力を必須にするため、required=Trueで上書き
    email = forms.EmailField(required=True)
    username = forms.CharField(required=True)

    class Meta:
        model = User
 
        fields = (
            "email", "password1", "password2", 
            "username","introduce","icon",
            )
 
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
 
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'お名前'
 
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレス'

        self.fields['icon'].widget.attrs['class'] = 'form-control'
        self.fields['icon'].widget.attrs['placeholder'] = 'アイコン画像'
         
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'パスワード'
  
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'パスワード（確認）'
        
        self.fields['introduce'].widget.attrs['class'] = 'form-control'
        self.fields['introduce'].widget.attrs['placeholder'] = '自己紹介文'

cosmicsns/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404
from .models import Posts, User
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from . import forms
from .forms import RegisterForm
# Create your views here.
class PostsList(LoginRequiredMixin,ListView):
    model = Posts
    template_name = "cosmicsns/posts_list.html"
    def get_queryset(self):
        object_list = Posts.objects.all()
        object_list = object_list.order_by('postedtime')
        object_list = object_list.reverse()
        return object_list

class TweetView(LoginRequiredMixin, CreateView):
    model = Posts
    fields = ('message',)
    template_name = 'cosmicsns/tweet.html'
    success_url = reverse_lazy('cosmicsns:list')
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class UserInfoView(LoginRequiredMixin,DetailView):
    model = User
    template_name = "cosmicsns/userinfo.html"
    
class UserEditView(LoginRequiredMixin,UpdateView):
    model = User
    template_name = "cosmicsns/user_edit.html"
    fields = ('username', 'introduce', 'icon')
    success_url = reverse_lazy("cosmicsns:list")
    
class UserPostsView(LoginRequiredMixin,ListView):
    context_object_name = "posts"
    template_name = "cosmicsns/userposts.html"
    def get_queryset(self):
        return Posts.objects.filter(author=self.request.user).order_by('postedtime').reverse()
    
class LoginView(LoginView):
    form_class = forms.LoginForm
    template_name = "cosmicsns/login.html"

class LogoutView(LogoutView):
    template_name = "cosmicsns/logout.html"
    
class UserCreateView(CreateView):
    form_class = RegisterForm
    template_name = "cosmicsns/create.html"
    success_url = reverse_lazy("cosmicsns:login")
    
    

cosmicsns/templates/cosmicsns/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>LOGIN</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
  <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
</head>
  <style type="text/css">
      body{
     background: #dcdcdc;
	  }
      button.btn--white {
			color: #fff;
			background-color: #bccccc;
			border-bottom: 5px solid #000000;
		}
		button.btn--white:hover {
			margin-top: 3px;
			color: #fff;
			background: #bbbbbb;
			border-bottom: 2px solid #000000;
		}
		button.btn--shadow {
			-webkit-box-shadow: 0 3px 5px rgba(0, 0, 0, .3);
			box-shadow: 0 3px 5px rgba(0, 0, 0, .3);
		}
		body {
        background-color: #dcdcdc;
        font-family: 'Ubuntu', sans-serif;
    }
    
    .main {
        background-color: #FFFFFF;
        width: 400px;
        height: 400px;
        margin: 7em auto;
        border-radius: 1.5em;
        box-shadow: 0px 11px 35px 2px rgba(0, 0, 0, 0.14);
        text-align:center;
    }
    
    .sign {
        padding-top: 40px;
        color: #8C55AA;
        font-family: 'Ubuntu', sans-serif;
        font-weight: bold;
        font-size: 23px;
    }
    
    .un {
    width: 76%;
    color: rgb(38, 50, 56);
    font-weight: 700;
    font-size: 14px;
    letter-spacing: 1px;
    background: rgba(136, 126, 126, 0.04);
    padding: 10px 20px;
    border: none;
    border-radius: 20px;
    outline: none;
    box-sizing: border-box;
    border: 2px solid rgba(0, 0, 0, 0.02);
    margin-bottom: 50px;
    margin-left: 46px;
    text-align: center;
    margin-bottom: 27px;
    font-family: 'Ubuntu', sans-serif;
    }
    
    form.form1 {
        padding-top: 40px;
    }
    
    .pass {
            width: 76%;
    color: rgb(38, 50, 56);
    font-weight: 700;
    font-size: 14px;
    letter-spacing: 1px;
    background: rgba(136, 126, 126, 0.04);
    padding: 10px 20px;
    border: none;
    border-radius: 20px;
    outline: none;
    box-sizing: border-box;
    border: 2px solid rgba(0, 0, 0, 0.02);
    margin-bottom: 50px;
    margin-left: 46px;
    text-align: center;
    margin-bottom: 27px;
    font-family: 'Ubuntu', sans-serif;
    }
    
   
    .un:focus, .pass:focus {
        border: 2px solid rgba(0, 0, 0, 0.18) !important;
        
    }
    
    .submit {
      cursor: pointer;
        border-radius: 5em;
        color: #fff;
        background: linear-gradient(to right, #9C27B0, #E040FB);
        border: 0;
        padding-left: 40px;
        padding-right: 40px;
        padding-bottom: 10px;
        padding-top: 10px;
        font-family: 'Ubuntu', sans-serif;
        margin-left: 35%;
        font-size: 13px;
        box-shadow: 0 0 20px 1px rgba(0, 0, 0, 0.04);
    }
    
    .forgot {
        text-shadow: 0px 0px 3px rgba(117, 117, 117, 0.12);
        color: #E1BEE7;
        padding-top: 15px;
    }
    
    a {
        text-shadow: 0px 0px 3px rgba(117, 117, 117, 0.12);
        color: #000000;
        text-decoration: none
    }
    
    @media (max-width: 600px) {
        .main {
            border-radius: 0px;
        }
</style>
</head>
<body>
	<div class="main" class="form1">
    <form action="" method="POST">
    <br>
    <br>
        <a align="center" style="font-size:30pt;font-weight:bold;">Sign in</a>
			<p><br></p>
        {% csrf_token %}
        {{ form.as_p }}
              <br>
         	 	<br>
        <button type="submit">ログイン</button>
    </form>
    </div>
    <a href="{% url 'cosmicsns:create' %}" >アカウントを新規作成</a>
</body>
</html>

cosmicsns/templates/cosmicsns/posts_list.html
{% extends "base.html" %}
{% load static %}
{% block title %} Club House {% endblock %}
{% block main %}
  <style type="text/css">
 h1{
    padding: 1.5rem;
    color: #111;
    background: #01e4e9;
    -webkit-boxshadow: 5px 5px 0 #00a4e9;
    box-shadow: 5px 5px 0 #00a4e9;
    text-align: center;
    text-shadow: 2px 2px 3px #ffffff;
 }
 .border_spread_btn {
    position: relative;
    display: inline-block;
    color: #1B1B1B;
    text-decoration: none;
 }
 .border_spread_btn:hover {
    cursor: pointer;
    text-decoration: none;
 }
 .border_spread_btn::after {
    position: absolute;
    bottom: -4px;
    left: 0;
    content: '';
    width: 100%;
    height: 2px;
    background: #333;
    transform: scale(0.5, 1);
    transform-origin: center top;
    transition: transform .3s;
 }
 .border_spread_btn:hover::after {
    transform: scale(1, 1);
 }

         body{
          background: #dcdcdc;
        }
    
        .boxes {
          margin: auto;
          padding: 5px;
          background: #dcdcdc;
        }
    
        table{
          text-align: center;
          border-collapse: collapse;
        } 
        table td, table th{
          border: solid 1px black;
        }
    
        /*Checkboxes styles*/
        input[type="checkbox"] { display: none; }

        input[type="checkbox"] + label {
          position: relative;
          padding-left: 21px;
          padding-right: 20px;
          margin-bottom: 20px;
          font: 14px/20px 'Open Sans', Arial, sans-serif;
          color: #000;
          cursor: pointer;
          -webkit-user-select: none;
          -moz-user-select: none;
          -ms-user-select: none;
        }

        input[type="checkbox"] + label:last-child { margin-bottom: 0; }

        input[type="checkbox"] + label:before {
          content: '';
          width: 20px;
          height: 20px;
          border: 1px solid #0066ff;//#6cc0e5;
          position: absolute;
          left: 0;
          top: 0;
          opacity: .6;
          -webkit-transition: all .12s, border-color .08s;
          transition: all .12s, border-color .08s;
        }

        input[type="checkbox"]:checked + label:before {
          width: 10px;
          top: -5px;
          left: 5px;
          border-radius: 0;
          opacity: 1;
          border-top-color: transparent;
          border-left-color: transparent;
          -webkit-transform: rotate(45deg);
          transform: rotate(45deg);
        }
        input[type="text"]:focus {
          background-color: #ffffe0;
        }

        input[type="date"]:focus {
          background-color: #ffffe0;
        }

      button.btn--white {
			color: #fff;
			background-color: #bccccc;
			border-bottom: 5px solid #000000;
		}
		button.btn--white:hover {
			margin-top: 3px;
			color: #fff;
			background: #bbbbbb;
			border-bottom: 2px solid #000000;
		}
		button.btn--shadow {
			-webkit-box-shadow: 0 3px 5px rgba(0, 0, 0, .3);
			box-shadow: 0 3px 5px rgba(0, 0, 0, .3);
		}
	  table{
	     text-align: center;
	     border-collapse: collapse;
	  } 
	  table td{
	     border: solid 1px black;
	     background: snow;
	  }
	  table th{
	     border: solid 1px black;
	  }
		.mgr-200{
		    margin-right : 200px;
		}
		.mgr-120{
		    margin-right : 120px;
		}
		.mgr-40{
		    margin-right : 40px;
		}
    
      .username{
        text-align: center;
        }
        .user-miniicon {
	    height: 40px;
    	width: 40px;
    	object-fit: cover;
    	border-radius: 50%;
    	border: 1.5px solid #eee;
		}        
        .user-icon {
	    height: 80px;
    	width: 80px;
    	object-fit: cover;
    	border-radius: 50%;
    	border: 1.5px solid #eee;
		}
		textarea{
    	 resize: none;
    	 width:100%;
		height:8em;
 		 }
 		 textarea:focus {
	   		background-color: #ffffe0;
		  }
		  td,textarea {
		    margin: 0;
		    padding: 0;
		    box-sizing: border-box;
		    border: none;
			-webkit-box-sizing:border-box;
			}
	</style>
<br>	
<p style="font-size:30px;text-align:center;" >現在<a href="{% url 'cosmicsns:useredit' user.pk %}">
			{% if user.icon %}
			<img src="{{ user.icon.url }}" class="user-icon">
			{% else %}
			<img src="{% static 'images/default.jpeg' %}" class="user-miniicon">
			{% endif%}</a>
			<span style="font-style: italic">{{ user.username }}</span> としてログインしています</p>
<br>
 <p><a href="{% url 'cosmicsns:tweet' %}" class="border_spread_btn">Grumble</a></p>
<table class="table">
	<thead class="thead-dark">
		<tr>
			<th>ユーザー</th>
			<th>投稿</th>
			<th>投稿日時</th>
		</tr>
	</thead>
	<tbody>
	{% for item in object_list %}
		<tr>
			<td scope="row">{{ item.author.username }}
			
			{% if item.author.username == user.username %}
			<a href="{% url 'cosmicsns:userposts' item.author.pk %}">
			{% else %}
			<a href="{% url 'cosmicsns:userinfo' item.author.pk %}">
			{% endif %}
			
			{% if item.author.icon %}
			<img src="{{ item.author.icon.url }}" class="user-icon">
			{% else %}
			<img src="{% static 'images/default.jpeg' %}" class="user-icon">
			{% endif %}
			</td>
			<td><textarea readonly>{{ item.message }}</textarea></td>
			<td>{{ item.postedtime }}</td>
		</tr>
	{% endfor %}
	</tbody>
</table>
 <p align="right"><a href="{% url 'cosmicsns:logout' %}" class="border_spread_btn">ログアウト</a></p>
{% endblock %}

cosmicsns/templates/cosmicsns/tweet.html
{% extends "base.html" %}

{% block title %} 投稿する {% endblock %}
 
{% block main %}
  <style>
  body{
     background: #dcdcdc;        
  }
  textarea{
   	resize: none;
	width: 20em;
	height: 25em;
  }
  h1{
     padding: 1.5rem;
     color: #111;
     background: #01e4e9;
     -webkit-boxshadow: 5px 5px 0 #00a4e9;
     box-shadow: 5px 5px 0 #00a4e9;
     text-align: center;
     text-shadow: 2px 2px 3px #ffffff;
  }

      button.btn--white {
			color: #fff;
			background-color: #bccccc;
			border-bottom: 5px solid #000000;
		}
		button.btn--white:hover {
			margin-top: 3px;
			color: #fff;
			background: #bbbbbb;
			border-bottom: 2px solid #000000;
		}
		button.btn--shadow {
			-webkit-box-shadow: 0 3px 5px rgba(0, 0, 0, .3);
			box-shadow: 0 3px 5px rgba(0, 0, 0, .3);
		}
  input:focus {
   background-color: #ffffe0;
  }

  textarea:focus {
   background-color: #ffffe0;
  }
.form1 {
    display: flex;
    justify-content: center;
     align-items: center;
     background-color: #dcdcdc;
}
.back{
     font-size: 50px; 
 }

 </style>

 <p class="back"><a href="{% url 'cosmicsns:list' %}">←</a></p>
<div class="form1">
 <form action="{% url 'cosmicsns:tweet' %}" method="post">
  {% csrf_token %}


 <table>
    <tr>
     <th>投稿内容</th>
     <td><textarea name="message" placeholder="200文字以内" maxlength="200" required></textarea></td>
    </tr>

 </table>
 <button type="submit" class="btn btn--white btn--cubic btn--shadow">送信する</button>
 </form>
</div>
{% endblock %}

cosmicsns/templates/cosmicsns/userinfo.html
{% extends "base.html" %}
{% load static %}
{% block title %} Club House {% endblock %}
{% block main %}
  <style type="text/css">
 h1{
    padding: 1.5rem;
    color: #111;
    background: #01e4e9;
    -webkit-boxshadow: 5px 5px 0 #00a4e9;
    box-shadow: 5px 5px 0 #00a4e9;
    text-align: center;
    text-shadow: 2px 2px 3px #ffffff;
 }
 .border_spread_btn {
    position: relative;
    display: inline-block;
    color: #1B1B1B;
    text-decoration: none;
 }
 .border_spread_btn:hover {
    cursor: pointer;
    text-decoration: none;
 }
 .border_spread_btn::after {
    position: absolute;
    bottom: -4px;
    left: 0;
    content: '';
    width: 100%;
    height: 2px;
    background: #333;
    transform: scale(0.5, 1);
    transform-origin: center top;
    transition: transform .3s;
 }
 .border_spread_btn:hover::after {
    transform: scale(1, 1);
 }

         body{
          background: #dcdcdc;
        }
    
        .boxes {
          margin: auto;
          padding: 5px;
          background: #dcdcdc;
        }
    
        table{
          text-align: center;
          border-collapse: collapse;
        } 
        table td, table th{
          border: solid 1px black;
        }
    
        /*Checkboxes styles*/
        input[type="checkbox"] { display: none; }

        input[type="checkbox"] + label {
          position: relative;
          padding-left: 21px;
          padding-right: 20px;
          margin-bottom: 20px;
          font: 14px/20px 'Open Sans', Arial, sans-serif;
          color: #000;
          cursor: pointer;
          -webkit-user-select: none;
          -moz-user-select: none;
          -ms-user-select: none;
        }

        input[type="checkbox"] + label:last-child { margin-bottom: 0; }

        input[type="checkbox"] + label:before {
          content: '';
          width: 20px;
          height: 20px;
          border: 1px solid #0066ff;//#6cc0e5;
          position: absolute;
          left: 0;
          top: 0;
          opacity: .6;
          -webkit-transition: all .12s, border-color .08s;
          transition: all .12s, border-color .08s;
        }

        input[type="checkbox"]:checked + label:before {
          width: 10px;
          top: -5px;
          left: 5px;
          border-radius: 0;
          opacity: 1;
          border-top-color: transparent;
          border-left-color: transparent;
          -webkit-transform: rotate(45deg);
          transform: rotate(45deg);
        }
        input[type="text"]:focus {
          background-color: #ffffe0;
        }

        input[type="date"]:focus {
          background-color: #ffffe0;
        }

      button.btn--white {
			color: #fff;
			background-color: #bccccc;
			border-bottom: 5px solid #000000;
		}
		button.btn--white:hover {
			margin-top: 3px;
			color: #fff;
			background: #bbbbbb;
			border-bottom: 2px solid #000000;
		}
		button.btn--shadow {
			-webkit-box-shadow: 0 3px 5px rgba(0, 0, 0, .3);
			box-shadow: 0 3px 5px rgba(0, 0, 0, .3);
		}
	  table{
	     text-align: center;
	     border-collapse: collapse;
	  } 
	  table td{
	     border: solid 1px black;
	     background: snow;
	  }
	  table th{
	     border: solid 1px black;
	  }
		.mgr-200{
		    margin-right : 200px;
		}
		.mgr-120{
		    margin-right : 120px;
		}
		.mgr-40{
		    margin-right : 40px;
		}
    
      .username{
        text-align: center;
        font-size: 100px; 
            display: inline;
        }
        
        .user-icon {
	    height: 150px;
    	width: 150px;
    	object-fit: cover;
    	border-radius: 50%;
    	border: 1.5px solid #eee;
    	display: inline;
		}
		
		.userintro{
        font-size: 20px;
        text-align: center;
        }
        
		.back{
        font-size: 50px; 
        }
	</style>
	<p class="back"><a href="{% url 'cosmicsns:list' %}">←</a></p>
	<div class="user-icon">
			{% if user.icon %}
			<img src="{{ user.icon.url }}" class="user-icon">
			{% else %}
			<img src="{% static 'images/default.jpeg' %}" class="user-icon">
			{% endif %}
	</div>
	<div class="username">{{ user.username }}</div>
	{% if user.introduce %}
	<div class="userintro">{{ user.introduce }}</div>
	{% endif %}
	
</table>
 <p align="right"><a href="{% url 'cosmicsns:logout' %}" class="border_spread_btn">ログアウト</a></p>
{% endblock %}

cosmicsns/templates/cosmicsns/userposts.html
{% extends "base.html" %}
{% load static %}
{% block title %} Club House {% endblock %}
{% block main %}
  <style type="text/css">
 h1{
    padding: 1.5rem;
    color: #111;
    background: #01e4e9;
    -webkit-boxshadow: 5px 5px 0 #00a4e9;
    box-shadow: 5px 5px 0 #00a4e9;
    text-align: center;
    text-shadow: 2px 2px 3px #ffffff;
 }
 .border_spread_btn {
    position: relative;
    display: inline-block;
    color: #1B1B1B;
    text-decoration: none;
 }
 .border_spread_btn:hover {
    cursor: pointer;
    text-decoration: none;
 }
 .border_spread_btn::after {
    position: absolute;
    bottom: -4px;
    left: 0;
    content: '';
    width: 100%;
    height: 2px;
    background: #333;
    transform: scale(0.5, 1);
    transform-origin: center top;
    transition: transform .3s;
 }
 .border_spread_btn:hover::after {
    transform: scale(1, 1);
 }

         body{
          background: #dcdcdc;
        }
    
        .boxes {
          margin: auto;
          padding: 5px;
          background: #dcdcdc;
        }
    
        table{
          text-align: center;
          border-collapse: collapse;
        } 
        table td, table th{
          border: solid 1px black;
        }
    
        /*Checkboxes styles*/
        input[type="checkbox"] { display: none; }

        input[type="checkbox"] + label {
          position: relative;
          padding-left: 21px;
          padding-right: 20px;
          margin-bottom: 20px;
          font: 14px/20px 'Open Sans', Arial, sans-serif;
          color: #000;
          cursor: pointer;
          -webkit-user-select: none;
          -moz-user-select: none;
          -ms-user-select: none;
        }

        input[type="checkbox"] + label:last-child { margin-bottom: 0; }

        input[type="checkbox"] + label:before {
          content: '';
          width: 20px;
          height: 20px;
          border: 1px solid #0066ff;//#6cc0e5;
          position: absolute;
          left: 0;
          top: 0;
          opacity: .6;
          -webkit-transition: all .12s, border-color .08s;
          transition: all .12s, border-color .08s;
        }

        input[type="checkbox"]:checked + label:before {
          width: 10px;
          top: -5px;
          left: 5px;
          border-radius: 0;
          opacity: 1;
          border-top-color: transparent;
          border-left-color: transparent;
          -webkit-transform: rotate(45deg);
          transform: rotate(45deg);
        }
        input[type="text"]:focus {
          background-color: #ffffe0;
        }

        input[type="date"]:focus {
          background-color: #ffffe0;
        }

      button.btn--white {
			color: #fff;
			background-color: #bccccc;
			border-bottom: 5px solid #000000;
		}
		button.btn--white:hover {
			margin-top: 3px;
			color: #fff;
			background: #bbbbbb;
			border-bottom: 2px solid #000000;
		}
		button.btn--shadow {
			-webkit-box-shadow: 0 3px 5px rgba(0, 0, 0, .3);
			box-shadow: 0 3px 5px rgba(0, 0, 0, .3);
		}
	  table{
	     text-align: center;
	     border-collapse: collapse;
	  } 
	  table td{
	     border: solid 1px black;
	     background: snow;
	  }
	  table th{
	     border: solid 1px black;
	  }
		.mgr-200{
		    margin-right : 200px;
		}
		.mgr-120{
		    margin-right : 120px;
		}
		.mgr-40{
		    margin-right : 40px;
		}
    
      .username{
        text-align: center;
        font-size: 100px; 
            display: inline;
        }
        
        .user-icon {
	    height: 150px;
    	width: 150px;
    	object-fit: cover;
    	border-radius: 50%;
    	border: 1.5px solid #eee;
    	display: inline;
		}
		
		.userintro{
        font-size: 20px;
        text-align: center;
        }
        
		.back{
        font-size: 50px; 
        }
        textarea{
    	 resize: none;
    	 width:100%;
		height:8em;
 		 }
 		 textarea:focus {
	   		background-color: #ffffe0;
		  }
		  td,textarea {
		    margin: 0;
		    padding: 0;
		    box-sizing: border-box;
		    border: none;
			-webkit-box-sizing:border-box;
			}
	.user-icon {
	height: 150px;
    	width: 150px;
    	object-fit: cover;
    	border-radius: 50%;
    	border: 1.5px solid #eee;
		}
	 .user-icon2 {
	height: 80px;
    	width: 80px;
    	object-fit: cover;
    	border-radius: 50%;
    	border: 1.5px solid #eee;
	}
	</style>
	<p class="back"><a href="{% url 'cosmicsns:list' %}">←</a></p>
 	<p><a href="{% url 'cosmicsns:tweet' %}" class="border_spread_btn">Grumble</a></p>
	<div class="user-icon">
			{% if user.icon %}
			<img src="{{ user.icon.url }}" class="user-icon">
			{% else %}
			<img src="{% static 'images/default.jpeg' %}" class="user-icon">
			{% endif %}
	</div>
	<div class="username">{{ user.username }}</div>
	{% if user.introduce %}
	<div class="userintro">{{ user.introduce }}</div>
	{% endif %}
	<table class="table">
	<thead class="thead-dark">
		<tr>
			<th>ユーザー</th>
			<th>投稿</th>
			<th>投稿日時</th>
		</tr>
	</thead>
	<tbody>
	{% for item in posts %}
		<tr>
			<td scope="row">{{ item.author.username }}
			
			{% if item.author.icon %}
			<img src="{{ item.author.icon.url }}" class="user-icon2">
			{% else %}
			<img src="{% static 'images/default.jpeg' %}" class="user-icon2">
			{% endif %}
			</td>
			<td><textarea readonly>{{ item.message }}</textarea></td>
			<td>{{ item.postedtime }}</td>
		</tr>
	{% endfor %}
	</tbody>
</table>
</table>
 <p align="right"><a href="{% url 'cosmicsns:logout' %}" class="border_spread_btn">ログアウト</a></p>
{% endblock %}